name: Build .NET Framework App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restore NuGet packages
      run: nuget restore Aptor.sln

    - run: ls packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\build\

    - run: ls packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\build\net472\

    - run: ls packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\

    - name: Build solution
      run: msbuild Aptor.sln /p:Configuration=Release /p:DeployOnBuild=true

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: order-management-system-artifact
        path: Aptor\obj\Release\Package
